### ISSUE TITLE
Поддержка 28-ой версии ag-grid

### ISSUE THREAD

**Issue by stalex** [consta-design-system/ag-grid-adapter#17]
Проверить на совместимость с 28-ой версией ag-grid и в случае успеха поднять версию в dependencies.

**Comment by jqweryjson** [comment]
"@consta/ag-grid-adapter": "^1.0.3",
    "ag-grid-community": "^30.1.0",
    "ag-grid-react": "^30.1.0",
    
   При таком сочетании зависимостей (по сути просто latest) не работет скролл в таблицах. Может лучше сразу на 30 версию целиться?

**Comment by gizeasy** [comment]
Обновили до 30той
